recipes_1_cotton_dark = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":70 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_2':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_9':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_10':{'init_temp':60,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_10':{'init_temp':30,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_11':{'init_temp':50,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_11':{'init_temp':30,"final_temp":40 ,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_12':{'init_temp':40,"final_temp":40 ,"temp.grad":0 ,"Duration":14 ,"steam_flow_rate":0.2},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                        }


recipes_2_cotton_medium = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":70 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_2':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         }


recipes_3_cotton_light = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":70 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_2':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         }


recipes_4_polyester_dark = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":40 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_2':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_9':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_10':{'init_temp':60,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_10':{'init_temp':30,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_11':{'init_temp':50,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_11':{'init_temp':30,"final_temp":40 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'hold_12':{'init_temp':40,"final_temp":40 ,"temp.grad":0 ,"Duration":14 ,"steam_flow_rate":0.2},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         }

recipes_5_pc_dark = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":70 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_2':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_9':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_10':{'init_temp':60,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_10':{'init_temp':30,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_11':{'init_temp':50,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_11':{'init_temp':30,"final_temp":40 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'hold_12':{'init_temp':40,"final_temp":40 ,"temp.grad":0 ,"Duration":14 ,"steam_flow_rate":0.2},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         }


recipes_5_sample_shade = {'loading':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         'Stock heating_1':{'init_temp':30,"final_temp":70 ,"temp.grad":0 ,"Duration": 10,"steam_flow_rate":0.73},
                         'heating_1':{'init_temp':70,"final_temp":110 ,"temp.grad":3.5 ,"Duration": 12,"steam_flow_rate":0.38},
                         'hold_1':{'init_temp':110,"final_temp":110 ,"temp.grad":0,"Duration":11 ,"steam_flow_rate":0.02},
                         'cooling_1':{'init_temp':110,"final_temp":90 ,"temp.grad":2 ,"Duration":3 ,"steam_flow_rate":0},
                         'drain&stock_1':{'init_temp':30,"final_temp":70,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_2':{'init_temp':70,"final_temp":70 ,"temp.grad":0,"Duration":5,"steam_flow_rate":0.02},
                         'drain&stock_2':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_3':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7 ,"steam_flow_rate":0.02},
                         'drain&stock_3':{'init_temp':30,"final_temp":60,"temp.grad":0,"Duration": 10,"steam_flow_rate":0.73},
                         'hold_4':{'init_temp':60,"final_temp":60,"temp.grad":0,"Duration":100 ,"steam_flow_rate":0.02},
                         'drain&stock_4':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_5':{'init_temp':50,"final_temp":50,"temp.grad":0,"Duration":7,"steam_flow_rate":0.02},
                         'drain&stock_5':{'init_temp':30,"final_temp":50,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_6':{'init_temp':50,"final_temp": 50,"temp.grad":0,"Duration": 7,"steam_flow_rate":0.02},
                         'drain&stock_6':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.73},
                         'heating_2':{'init_temp':80,"final_temp":95,"temp.grad":3.5 ,"Duration":4 ,"steam_flow_rate":0.38},
                         'hold_7':{'init_temp':95,"final_temp":95,"temp.grad":0 ,"Duration":7 ,"steam_flow_rate":0.02},
                         'cooling_2':{'init_temp':95,"final_temp":90 ,"temp.grad":2 ,"Duration":10 ,"steam_flow_rate":0},
                         'drain&stock_7':{'init_temp':30,"final_temp":80,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_8':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10,"steam_flow_rate":0.02},
                         'drain&stock_8':{'init_temp':30,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_9':{'init_temp':80,"final_temp":80 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_9':{'init_temp':30,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_10':{'init_temp':60,"final_temp":60 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_10':{'init_temp':30,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.73},
                         'hold_11':{'init_temp':50,"final_temp":50 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0.02},
                         'drain&stock_11':{'init_temp':30,"final_temp":40 ,"temp.grad":0,"Duration":10,"steam_flow_rate":0.73},
                         'hold_12':{'init_temp':40,"final_temp":40 ,"temp.grad":0 ,"Duration":14 ,"steam_flow_rate":0.2},
                         'drain&unload':{'init_temp':0,"final_temp":0 ,"temp.grad":0 ,"Duration":10 ,"steam_flow_rate":0},
                         }